<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache License, Version 2.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/Apache-2.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apruve.com so we can send you a copy immediately.
 *
 * @category   Apruve
 * @package    Apruve_Payment
 * @copyright  Copyright (coffee) 2014 Apruve, Inc. (http://www.apruve.com).
 * @license    http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php $errors = $this->getErrors();
$this->getQuoteIsVirtual();
?>
<div class="page-title">
    <h1><?php echo $this->__('Review Order') ?></h1>
</div>
<?php if($errors): ?>
<div class="error-msg">
    <?php foreach($errors as $error) {
        echo $error.'<br/>';
    }
    ?>

</div>
<br/>
<?php endif;?>
<script type="text/javascript">
    var form = new VarienForm('order_review_form');
</script>

<div class="addresses" style="width: 100%; text-align: left;">
    <div class="col-1 info-set" style="width:45%; display: inline-block; float: left;">
        <h2 class="legend"> Billing Info</h2>
        <?php echo $this->getChild('billing')->setFieldNamePrefix('billing')->toHtml(); ?>
    </div>
    <?php if(!$this->getQuoteIsVirtual()) :?>
    <div class="col-2 info-set" style="width:45%; display: inline-block; float: right;">
        <h2 class="legend"> Shipping Info</h2>
        <?php echo $this->getChild('shipping')->setFieldNamePrefix('shipping')->toHtml(); ?>
    </div>
    <?php endif;?>
</div>
<div style="clear: both;"></div>


<?php if(!$this->getQuoteIsVirtual()) :?>
<div><?php echo $this->getChildHtml('shipping_method'); ?></div>
<?php endif;?>

<div class="apruve-review-order">
    <form method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
    <div class="info-set">
        <h2 class="legend"><?php echo $this->__('Items in Your Shopping Cart') ?><span class="separator"> | </span><a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Shopping Cart') ?></a></h2>
        <div id="details-reload">
            <?php echo $this->getChildHtml('details') ?>
        </div>
    </div>
        <?php echo $this->getChildHtml('agreements'); ?>
        <div class="buttons-set buttons-set-order" id="review-buttons-container">
            <button type="button" id="review_button" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="form.submit();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
            <span class="please-wait" id="review-please-wait" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
            </span>
        </div>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    function switchAddressBlockView(prefix) {
        var idAddressForm = prefix+'-address-form';
        var idAddressInfo = prefix+'-address-info';
        var form = $(idAddressForm);

        if(!form.visible()) {
            form.show();
            $(idAddressInfo).hide();
        } else {
            form.hide();
            $(idAddressInfo).show();
        }
    }

    //]]>
</script>