<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache License, Version 2.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/Apache-2.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apruve.com so we can send you a copy immediately.
 *
 * @category   Apruve
 * @package    Apruve_Payment
 * @copyright  Copyright (coffee) 2014 Apruve, Inc. (http://www.apruve.com).
 * @license    http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<div id="payment_form_apruvepayment">
    Press continue to review order.
    <input type="hidden" id="aprt" value="" name="payment[aprt]"/>
</div>

<?php
$helper = Mage::helper('apruvepayment');
$paymentRequestModel = $helper->getPaymentRequestApiModel();
?>

<script type="text/javascript">
    $$('label[for=p_method_apruvepayment]')[0].innerHTML += '<div id="apruveDiv" style="display: inline-block; position: absolute; margin-top: -3px; margin-left: 7px;"></div>';
    var sh = '<?php echo $paymentRequestModel->getSecureHash();?>';
    var pr = <?php echo $paymentRequestModel->getPaymentRequestJSON();?>;
    var shopperName = '<?php echo $paymentRequestModel->getShopperInfo('name');?>';
    var shopperEmail = '<?php echo $paymentRequestModel->getShopperInfo('email');?>';
    var autoSubmit = '<?php echo $helper->isAutoSubmit();?>';
    var oApruvePayment = new ApruvePayment(sh, pr, shopperName, shopperEmail, autoSubmit);
</script>

