<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache License, Version 2.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/Apache-2.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apruve.com so we can send you a copy immediately.
 *
 * @category   Apruve
 * @package    Apruve_Payment
 * @copyright  Copyright (coffee) 2014 Apruve, Inc. (http://www.apruve.com).
 * @license    http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<div id="payment_form_apruvepayment">
    <span class="please-wait" id="apruvepayment-please-wait">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please wait...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
    </span>
    <input type="hidden" id="aprt" value="" name="payment[aprt]"/>
</div>

<?php
$helper = Mage::helper('apruvepayment');
$paymentRequestModel = $helper->getPaymentRequestApiModel();
?>

<script type="text/javascript">
    (function() {
        $('p_method_apruvepayment').disable();
        function initApruve(url, callback) {
            var script = document.createElement("script");
            script.type = "text/javascript";
            if (script.readyState) {
                script.onreadystatechange = function () {
                    if (script.readyState == "loaded" || script.readyState == "complete") {
                        script.onreadystatechange = null;
                        callback()
                    }
                }
            } else {
                script.onreadystatechange = callback;
                script.onload = callback
            }
            script.src = url;
            document.body.appendChild(script)
        }

        function initPayment() {
            $$('label[for=p_method_apruvepayment]')[0].innerHTML += '<div id="apruveDiv" style="display: inline-block; position: absolute; margin-top: -3px; margin-left: 7px;"></div>';
            var sh = '<?php echo $paymentRequestModel->getSecureHash();?>';
            var pr = <?php echo $paymentRequestModel->getPaymentRequestJSON();?>;
            var shopperName = '<?php echo $paymentRequestModel->getShopperInfo('name');?>';
            var shopperEmail = '<?php echo $paymentRequestModel->getShopperInfo('email');?>';
            var autoSubmit = '<?php echo $helper->isAutoSubmit();?>';
            new ApruvePayment(sh, pr, shopperName, shopperEmail, autoSubmit);
        }

        if (typeof ApruvePayment === 'undefined') {
            initApruve(
                "<?php echo Mage::helper('apruvepayment')->getSrc();?>",
                function () {
                    if (document.readyState === "complete"
                        && apruve.apruveIFrame === null
                    ) apruve.initialize();
                    initApruve("<?php echo Mage::getBaseUrl('js') . 'Apruve/ApruvePayment.js';?>", initPayment)
                }
            );
        } else {
            initPayment();
        }
    })();
</script>

