<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Apache License, Version 2.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/Apache-2.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@apruve.com so we can send you a copy immediately.
 *
 * @category   Apruve
 * @package    Apruve_Payment
 * @copyright  Copyright (coffee) 2014 Apruve, Inc. (http://www.apruve.com).
 * @license    http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php
$helper = Mage::helper('apruvepayment');
$paymentApiModel = $helper->getPaymentApiModel();
?>

<div id="payment_form_apruvepayment">
    <input type="hidden" id="aprt" value="" name="payment[aprt]"/>
</div>

<script type="text/javascript">
    var sh = '<?php echo $paymentApiModel->getSecureHash();?>';
    var pr = <?php echo $paymentApiModel->getPaymentRequestJSON();?>;
    var shopperName = '<?php echo $paymentApiModel->getShopperInfo('name');?>';
    var shopperEmail = '<?php echo $paymentApiModel->getShopperInfo('email');?>';
    var autoSubmit = '<?php echo $helper->isAutoSubmit();?>';
    var paymentMethodCode = '<?php echo Apruve_ApruvePayment_Model_PaymentMethod::PAYMENT_METHOD_CODE; ?>';
    document.getElementById("aprt").value = aprt;

    Payment.prototype.save = Payment.prototype.save.wrap(function(save) {
        var validator = new Validation(this.form);
        if (this.validate() && validator.validate()) {
            // DO WHAT YOU WANT TO DO BEFORE SAVE
            var oApruvePayment = new ApruvePayment(sh, pr, shopperName, shopperEmail, autoSubmit, true);

            var paymentMethod = '';
            for(i in document.getElementsByName('payment[method]')) {
                if(document.getElementsByName('payment[method]').hasOwnProperty(i) && document.getElementsByName('payment[method]')[i].checked) {
                    paymentMethod = document.getElementsByName('payment[method]')[i].value;
                }
            }
            if(paymentMethod == paymentMethodCode && document.getElementById("aprt").value == ''){
                apruve.startCheckout();
            }
            if((paymentMethod == paymentMethodCode && document.getElementById("aprt").value !== '') || paymentMethod !== paymentMethodCode){
                    aprt = document.getElementById("aprt").value;
                    save(); // THIS WILL CALL CORE SAVE THAT WAS WRAPPED
                }
        }
    });
</script>

